// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropertiesWebService.DAL;

#nullable disable

namespace PropertiesWebService.DatabaseMigrator.Migrations
{
    [DbContext(typeof(PropertiesWebServiceDemoDbContext))]
    partial class PropertiesWebServiceDemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropertiesWebService.DAL.Entities.Dictionaries.DictPropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_DictPropertyType_Name");

                    b.ToTable("DictPropertyType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 8, 27, 11, 42, 50, 26, DateTimeKind.Utc).AddTicks(115),
                            IsActive = true,
                            Name = "Apartment"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 8, 27, 11, 42, 50, 26, DateTimeKind.Utc).AddTicks(120),
                            IsActive = true,
                            Name = "House"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 8, 27, 11, 42, 50, 26, DateTimeKind.Utc).AddTicks(121),
                            IsActive = true,
                            Name = "Condo"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 8, 27, 11, 42, 50, 26, DateTimeKind.Utc).AddTicks(122),
                            IsActive = true,
                            Name = "Villa"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 8, 27, 11, 42, 50, 26, DateTimeKind.Utc).AddTicks(124),
                            IsActive = true,
                            Name = "Cottage"
                        });
                });

            modelBuilder.Entity("PropertiesWebService.DAL.Entities.Dictionaries.DictSpaceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_DictSpaceType_Name");

                    b.ToTable("DictSpaceType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 8, 27, 11, 42, 50, 26, DateTimeKind.Utc).AddTicks(439),
                            IsActive = true,
                            Name = "Living Room"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 8, 27, 11, 42, 50, 26, DateTimeKind.Utc).AddTicks(441),
                            IsActive = true,
                            Name = "Bedroom"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 8, 27, 11, 42, 50, 26, DateTimeKind.Utc).AddTicks(442),
                            IsActive = true,
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 8, 27, 11, 42, 50, 26, DateTimeKind.Utc).AddTicks(443),
                            IsActive = true,
                            Name = "Office room"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 8, 27, 11, 42, 50, 26, DateTimeKind.Utc).AddTicks(445),
                            IsActive = true,
                            Name = "Garage"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 8, 27, 11, 42, 50, 26, DateTimeKind.Utc).AddTicks(446),
                            IsActive = true,
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 8, 27, 11, 42, 50, 26, DateTimeKind.Utc).AddTicks(447),
                            IsActive = true,
                            Name = "Balcony"
                        });
                });

            modelBuilder.Entity("PropertiesWebService.DAL.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Description")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Address" }, "IX_Property_Address");

                    b.HasIndex(new[] { "Address", "Price" }, "IX_Property_Address_Price");

                    b.HasIndex(new[] { "Price" }, "IX_Property_Price");

                    b.HasIndex(new[] { "TypeId" }, "IX_Property_TypeId");

                    b.HasIndex(new[] { "TypeId", "Address" }, "IX_Property_TypeId_Address");

                    b.HasIndex(new[] { "TypeId", "Price" }, "IX_Property_TypeId_Price");

                    b.ToTable("Property");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Ocean View Drive",
                            Description = "Modern apartment with stunning ocean views.",
                            Price = 1200.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "22 Maple Street",
                            Description = "Cozy house in a quiet suburban neighborhood.",
                            Price = 950.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "5 City Center Plaza",
                            Description = "Luxury condo in the heart of downtown.",
                            Price = 1800.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "77 Mountain Retreat",
                            Description = "Spacious villa nestled in the mountains.",
                            Price = 2500.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Address = "9 Lakeside Lane",
                            Description = "Charming cottage by the lake.",
                            Price = 1100.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            Address = "101 Riverside Avenue",
                            Description = "Apartment with river views and modern amenities.",
                            Price = 1300.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            Address = "33 Forest Path",
                            Description = "House surrounded by beautiful forest scenery.",
                            Price = 1050.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Address = "8 Grand Boulevard",
                            Description = "Condo with access to city attractions.",
                            Price = 2000.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Address = "12 Sunny Meadows",
                            Description = "Villa with large garden and sunny rooms.",
                            Price = 2300.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 10,
                            Address = "44 Hilltop Crescent",
                            Description = "Cottage with panoramic hilltop views.",
                            Price = 1150.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 11,
                            Address = "2 Seaside Promenade",
                            Description = "Apartment steps from the beach.",
                            Price = 1400.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            Address = "18 Country Lane",
                            Description = "House with spacious backyard in the countryside.",
                            Price = 980.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            Address = "6 Urban Heights",
                            Description = "Condo with skyline views.",
                            Price = 1750.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 14,
                            Address = "55 Vineyard Road",
                            Description = "Villa surrounded by vineyards.",
                            Price = 2600.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 15,
                            Address = "3 Harbor Point",
                            Description = "Cottage with harbor access.",
                            Price = 1200.0m,
                            TypeId = 5
                        });
                });

            modelBuilder.Entity("PropertiesWebService.DAL.Entities.Space", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Size")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PropertyId" }, "IX_Space_PropertyId");

                    b.HasIndex(new[] { "PropertyId", "Size" }, "IX_Space_PropertyId_Size");

                    b.HasIndex(new[] { "PropertyId", "TypeId" }, "IX_Space_PropertyId_TypeId");

                    b.HasIndex(new[] { "TypeId" }, "IX_Space_TypeId");

                    b.HasIndex(new[] { "TypeId", "Size" }, "IX_Space_TypeId_Size");

                    b.ToTable("Space");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Spacious living room with natural light. (Property 1)",
                            PropertyId = 1,
                            Size = 21.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 1)",
                            PropertyId = 1,
                            Size = 31.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Modern kitchen with high-end appliances. (Property 1)",
                            PropertyId = 1,
                            Size = 41.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Home office with inspiring views. (Property 1)",
                            PropertyId = 1,
                            Size = 51.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Secure garage with extra storage. (Property 1)",
                            PropertyId = 1,
                            Size = 61.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Beautiful garden with seasonal flowers. (Property 1)",
                            PropertyId = 1,
                            Size = 71.0m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Balcony perfect for morning coffee. (Property 1)",
                            PropertyId = 1,
                            Size = 81.0m,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 8,
                            Description = "Spacious living room with natural light. (Property 2)",
                            PropertyId = 2,
                            Size = 22.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 2)",
                            PropertyId = 2,
                            Size = 32.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Modern kitchen with high-end appliances. (Property 2)",
                            PropertyId = 2,
                            Size = 42.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 11,
                            Description = "Home office with inspiring views. (Property 2)",
                            PropertyId = 2,
                            Size = 52.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 12,
                            Description = "Secure garage with extra storage. (Property 2)",
                            PropertyId = 2,
                            Size = 62.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 13,
                            Description = "Spacious living room with natural light. (Property 3)",
                            PropertyId = 3,
                            Size = 23.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 3)",
                            PropertyId = 3,
                            Size = 33.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "Modern kitchen with high-end appliances. (Property 3)",
                            PropertyId = 3,
                            Size = 43.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 16,
                            Description = "Home office with inspiring views. (Property 3)",
                            PropertyId = 3,
                            Size = 53.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 17,
                            Description = "Secure garage with extra storage. (Property 3)",
                            PropertyId = 3,
                            Size = 63.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 18,
                            Description = "Beautiful garden with seasonal flowers. (Property 3)",
                            PropertyId = 3,
                            Size = 73.0m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 19,
                            Description = "Spacious living room with natural light. (Property 4)",
                            PropertyId = 4,
                            Size = 24.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 20,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 4)",
                            PropertyId = 4,
                            Size = 34.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 21,
                            Description = "Modern kitchen with high-end appliances. (Property 4)",
                            PropertyId = 4,
                            Size = 44.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 22,
                            Description = "Home office with inspiring views. (Property 4)",
                            PropertyId = 4,
                            Size = 54.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 23,
                            Description = "Secure garage with extra storage. (Property 4)",
                            PropertyId = 4,
                            Size = 64.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 24,
                            Description = "Beautiful garden with seasonal flowers. (Property 4)",
                            PropertyId = 4,
                            Size = 74.0m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 25,
                            Description = "Balcony perfect for morning coffee. (Property 4)",
                            PropertyId = 4,
                            Size = 84.0m,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 26,
                            Description = "Spacious living room with natural light. (Property 4)",
                            PropertyId = 4,
                            Size = 94.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 27,
                            Description = "Spacious living room with natural light. (Property 5)",
                            PropertyId = 5,
                            Size = 25.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 28,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 5)",
                            PropertyId = 5,
                            Size = 35.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 29,
                            Description = "Modern kitchen with high-end appliances. (Property 5)",
                            PropertyId = 5,
                            Size = 45.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 30,
                            Description = "Home office with inspiring views. (Property 5)",
                            PropertyId = 5,
                            Size = 55.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 31,
                            Description = "Secure garage with extra storage. (Property 5)",
                            PropertyId = 5,
                            Size = 65.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 32,
                            Description = "Beautiful garden with seasonal flowers. (Property 5)",
                            PropertyId = 5,
                            Size = 75.0m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 33,
                            Description = "Balcony perfect for morning coffee. (Property 5)",
                            PropertyId = 5,
                            Size = 85.0m,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 34,
                            Description = "Spacious living room with natural light. (Property 5)",
                            PropertyId = 5,
                            Size = 95.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 35,
                            Description = "Spacious living room with natural light. (Property 6)",
                            PropertyId = 6,
                            Size = 26.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 36,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 6)",
                            PropertyId = 6,
                            Size = 36.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 37,
                            Description = "Modern kitchen with high-end appliances. (Property 6)",
                            PropertyId = 6,
                            Size = 46.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 38,
                            Description = "Home office with inspiring views. (Property 6)",
                            PropertyId = 6,
                            Size = 56.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 39,
                            Description = "Secure garage with extra storage. (Property 6)",
                            PropertyId = 6,
                            Size = 66.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 40,
                            Description = "Beautiful garden with seasonal flowers. (Property 6)",
                            PropertyId = 6,
                            Size = 76.0m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 41,
                            Description = "Balcony perfect for morning coffee. (Property 6)",
                            PropertyId = 6,
                            Size = 86.0m,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 42,
                            Description = "Spacious living room with natural light. (Property 7)",
                            PropertyId = 7,
                            Size = 27.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 43,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 7)",
                            PropertyId = 7,
                            Size = 37.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 44,
                            Description = "Modern kitchen with high-end appliances. (Property 7)",
                            PropertyId = 7,
                            Size = 47.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 45,
                            Description = "Home office with inspiring views. (Property 7)",
                            PropertyId = 7,
                            Size = 57.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 46,
                            Description = "Secure garage with extra storage. (Property 7)",
                            PropertyId = 7,
                            Size = 67.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 47,
                            Description = "Beautiful garden with seasonal flowers. (Property 7)",
                            PropertyId = 7,
                            Size = 77.0m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 48,
                            Description = "Balcony perfect for morning coffee. (Property 7)",
                            PropertyId = 7,
                            Size = 87.0m,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 49,
                            Description = "Spacious living room with natural light. (Property 8)",
                            PropertyId = 8,
                            Size = 28.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 50,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 8)",
                            PropertyId = 8,
                            Size = 38.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 51,
                            Description = "Modern kitchen with high-end appliances. (Property 8)",
                            PropertyId = 8,
                            Size = 48.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 52,
                            Description = "Home office with inspiring views. (Property 8)",
                            PropertyId = 8,
                            Size = 58.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 53,
                            Description = "Secure garage with extra storage. (Property 8)",
                            PropertyId = 8,
                            Size = 68.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 54,
                            Description = "Beautiful garden with seasonal flowers. (Property 8)",
                            PropertyId = 8,
                            Size = 78.0m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 55,
                            Description = "Balcony perfect for morning coffee. (Property 8)",
                            PropertyId = 8,
                            Size = 88.0m,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 56,
                            Description = "Spacious living room with natural light. (Property 8)",
                            PropertyId = 8,
                            Size = 98.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 57,
                            Description = "Spacious living room with natural light. (Property 9)",
                            PropertyId = 9,
                            Size = 29.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 58,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 9)",
                            PropertyId = 9,
                            Size = 39.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 59,
                            Description = "Modern kitchen with high-end appliances. (Property 9)",
                            PropertyId = 9,
                            Size = 49.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 60,
                            Description = "Home office with inspiring views. (Property 9)",
                            PropertyId = 9,
                            Size = 59.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 61,
                            Description = "Secure garage with extra storage. (Property 9)",
                            PropertyId = 9,
                            Size = 69.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 62,
                            Description = "Beautiful garden with seasonal flowers. (Property 9)",
                            PropertyId = 9,
                            Size = 79.0m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 63,
                            Description = "Balcony perfect for morning coffee. (Property 9)",
                            PropertyId = 9,
                            Size = 89.0m,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 64,
                            Description = "Spacious living room with natural light. (Property 9)",
                            PropertyId = 9,
                            Size = 99.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 65,
                            Description = "Spacious living room with natural light. (Property 10)",
                            PropertyId = 10,
                            Size = 30.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 66,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 10)",
                            PropertyId = 10,
                            Size = 40.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 67,
                            Description = "Modern kitchen with high-end appliances. (Property 10)",
                            PropertyId = 10,
                            Size = 50.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 68,
                            Description = "Home office with inspiring views. (Property 10)",
                            PropertyId = 10,
                            Size = 60.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 69,
                            Description = "Secure garage with extra storage. (Property 10)",
                            PropertyId = 10,
                            Size = 70.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 70,
                            Description = "Beautiful garden with seasonal flowers. (Property 10)",
                            PropertyId = 10,
                            Size = 80.0m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 71,
                            Description = "Balcony perfect for morning coffee. (Property 10)",
                            PropertyId = 10,
                            Size = 90.0m,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 72,
                            Description = "Spacious living room with natural light. (Property 10)",
                            PropertyId = 10,
                            Size = 100.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 73,
                            Description = "Spacious living room with natural light. (Property 11)",
                            PropertyId = 11,
                            Size = 31.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 74,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 11)",
                            PropertyId = 11,
                            Size = 41.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 75,
                            Description = "Modern kitchen with high-end appliances. (Property 11)",
                            PropertyId = 11,
                            Size = 51.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 76,
                            Description = "Home office with inspiring views. (Property 11)",
                            PropertyId = 11,
                            Size = 61.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 77,
                            Description = "Secure garage with extra storage. (Property 11)",
                            PropertyId = 11,
                            Size = 71.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 78,
                            Description = "Beautiful garden with seasonal flowers. (Property 11)",
                            PropertyId = 11,
                            Size = 81.0m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 79,
                            Description = "Spacious living room with natural light. (Property 12)",
                            PropertyId = 12,
                            Size = 32.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 80,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 12)",
                            PropertyId = 12,
                            Size = 42.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 81,
                            Description = "Modern kitchen with high-end appliances. (Property 12)",
                            PropertyId = 12,
                            Size = 52.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 82,
                            Description = "Home office with inspiring views. (Property 12)",
                            PropertyId = 12,
                            Size = 62.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 83,
                            Description = "Secure garage with extra storage. (Property 12)",
                            PropertyId = 12,
                            Size = 72.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 84,
                            Description = "Spacious living room with natural light. (Property 13)",
                            PropertyId = 13,
                            Size = 33.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 85,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 13)",
                            PropertyId = 13,
                            Size = 43.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 86,
                            Description = "Modern kitchen with high-end appliances. (Property 13)",
                            PropertyId = 13,
                            Size = 53.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 87,
                            Description = "Home office with inspiring views. (Property 13)",
                            PropertyId = 13,
                            Size = 63.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 88,
                            Description = "Secure garage with extra storage. (Property 13)",
                            PropertyId = 13,
                            Size = 73.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 89,
                            Description = "Beautiful garden with seasonal flowers. (Property 13)",
                            PropertyId = 13,
                            Size = 83.0m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 90,
                            Description = "Balcony perfect for morning coffee. (Property 13)",
                            PropertyId = 13,
                            Size = 93.0m,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 91,
                            Description = "Spacious living room with natural light. (Property 13)",
                            PropertyId = 13,
                            Size = 103.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 92,
                            Description = "Spacious living room with natural light. (Property 14)",
                            PropertyId = 14,
                            Size = 34.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 93,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 14)",
                            PropertyId = 14,
                            Size = 44.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 94,
                            Description = "Modern kitchen with high-end appliances. (Property 14)",
                            PropertyId = 14,
                            Size = 54.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 95,
                            Description = "Home office with inspiring views. (Property 14)",
                            PropertyId = 14,
                            Size = 64.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 96,
                            Description = "Secure garage with extra storage. (Property 14)",
                            PropertyId = 14,
                            Size = 74.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 97,
                            Description = "Beautiful garden with seasonal flowers. (Property 14)",
                            PropertyId = 14,
                            Size = 84.0m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 98,
                            Description = "Spacious living room with natural light. (Property 15)",
                            PropertyId = 15,
                            Size = 35.0m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 99,
                            Description = "Cozy master bedroom with ensuite bathroom. (Property 15)",
                            PropertyId = 15,
                            Size = 45.0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 100,
                            Description = "Modern kitchen with high-end appliances. (Property 15)",
                            PropertyId = 15,
                            Size = 55.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 101,
                            Description = "Home office with inspiring views. (Property 15)",
                            PropertyId = 15,
                            Size = 65.0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 102,
                            Description = "Secure garage with extra storage. (Property 15)",
                            PropertyId = 15,
                            Size = 75.0m,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 103,
                            Description = "Beautiful garden with seasonal flowers. (Property 15)",
                            PropertyId = 15,
                            Size = 85.0m,
                            TypeId = 6
                        });
                });

            modelBuilder.Entity("PropertiesWebService.DAL.Entities.Property", b =>
                {
                    b.HasOne("PropertiesWebService.DAL.Entities.Dictionaries.DictPropertyType", "Type")
                        .WithMany("Properties")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Property_TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PropertiesWebService.DAL.Entities.Space", b =>
                {
                    b.HasOne("PropertiesWebService.DAL.Entities.Property", "Property")
                        .WithMany("Spaces")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Space_PropertyId");

                    b.HasOne("PropertiesWebService.DAL.Entities.Dictionaries.DictSpaceType", "Type")
                        .WithMany("Spaces")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Space_TypeId");

                    b.Navigation("Property");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PropertiesWebService.DAL.Entities.Dictionaries.DictPropertyType", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("PropertiesWebService.DAL.Entities.Dictionaries.DictSpaceType", b =>
                {
                    b.Navigation("Spaces");
                });

            modelBuilder.Entity("PropertiesWebService.DAL.Entities.Property", b =>
                {
                    b.Navigation("Spaces");
                });
#pragma warning restore 612, 618
        }
    }
}
